---
title: "analyses"
output: 
  html_document:
    theme: cosmo
    toc: true
    toc_depth: 4
    toc_float:
      collapsed: false
---

# Libraries
```{r load-libs, message=F, warning=F}
library(rio)
library(here)
library(tidyverse)
library(janitor)
library(ggplot2)
```

# Data
```{r}
dfc <- import(here("analysis-data", "cleaned-data.csv"))
```

# Descriptives

# Inferential
## IMRI Log Model
### Coding for Above Average
#### control only
```{r}
imriiz0_model1 = glm(data = dfc, formula = as.factor(imri_iz0) ~ conservatism_f,
                     family = "binomial")

summary(imriiz0_model1)
```

#### w/ predictor
```{r}
imriiz0_model2 = glm(data = dfc, formula = as.factor(imri_iz0) ~ sc_scored + 
                       conservatism_f, family = "binomial")

summary(imriiz0_model2)
```

```{r eval=F}
comp_iz0 <- anova(imriiz0_model1, imriiz0_model2)

summary(comp_iz0)
```

### Coding for Endpoint Bias
#### control only
```{r}
imriie_model1 = glm(data = dfc, formula = as.factor(imri_ie) ~ conservatism_f, 
                    family = "binomial")

summary(imriie_model1)
```

#### w/ predictor
```{r}
imriie_model2 = glm(data = dfc, formula = as.factor(imri_ie) ~ sc_scored + 
                      conservatism_f, family = "binomial")

summary(imriie_model2)
```

```{r eval=F}
comp_ie <- anova(imriie_model1, imriie_model2)

summary(comp_ie)
```

