---
title: "comp-lib"
output: html_document
---

# load libraries
```{r}
library(tidyverse)
library(here)
library(rio)

```

# import data
```{r}
df_ml1 <- import(here("comp-data", "sci-cur-cr-lib1-data.csv")) %>% 
  mutate(batch = "lib1")
df_ml2 <- import(here("comp-data", "scicur-comp-lib2.csv")) %>% 
  mutate(batch = "lib2")
df_mc1 <- import(here("comp-data", "scicur-comp-con-071822-1548.csv")) %>% 
  mutate(batch = "con1")
# df_mc2 <- import(here("comp-data", "scicur-comp-con1-071922.csv")) %>% 
#   mutate(batch = "con2")
df_mc3 <- import(here("comp-data", "scicur-comp-con2-072522.csv")) %>% 
  mutate(batch = "con3")
df_q <- import(here("comp-data", "scicur-q-072522.csv"))

df_m <- rbind(df_ml1, df_ml2, df_mc1, df_mc3) 
```

```{r}
df_q %>% 
  mutate(dup = duplicated(id))
  filter(duplicated(.) == F)

df_q %>% 
  filter(duplicated(.) == T)

df_m <- df_m %>% 
  clean_mturk()

df_q %>% 
  filter("ID" == "A1IJ56N5Z4TT46")
```

```{r}
df_match <- match_dfs(df_mc1, df_qc) %>% 
  clean_matchdf()

df_matchs <- df_match %>% 
  filter(submitted == 1)

approve <- df_match %>% 
  filter(submitted == 1 & match == 1)

reject <- df_match %>% 
  filter(submitted == 0)
```


```{r}
matched <- mtchr(df_m, df_q, label_m = "batch", kill_switch = F)
```

