---
title: "pres-scraps"
output: html_document
---

```{r lib, echo=F}
# Load libraries
library(rio)
library(here)
library(tidyverse)
library(ggplot2)
library(lme4)
library(knitr)
library(janitor)
library(Hmisc)
library(reshape2)
library(viridis)
library(kableExtra)
```

```{r data, echo=F}
# Import data
dfp_clean <- import(here("analysis-data", "cleaned-data.csv"))
dfp_prepped <- import(here("analysis-data", "prepped-for-analysis-data.csv")) %>% 
  janitor::clean_names()

dfp_lc <- dfp_prepped %>% 
  filter(conservatism_f != 4 | con != 0)
```

```{r n, echo=F}
n_total <- dfp_prepped %>% 
  nrow()

n_by_con <- dfp_prepped %>% 
  group_by(con) %>% 
  summarise(n = n(),
            percent = round(100 * (n()/nrow(dfp_prepped)), 2))

n_by_con_lc <- dfp_lc %>% 
  group_by(con) %>% 
  summarise(n = n(),
            percent = round(100 * (n()/nrow(dfp_lc)), 2))
```

```{r age, echo=F}
df_age <- dfp_prepped %>% 
  select(dem_age_b) %>% 
  psych::describe()

m_age <- df_age$mean %>% 
  round(2)
min_age <- df_age$min %>% 
  round(2)
max_age <- df_age$max %>% 
  round(2)
```

```{r gender, echo=F}
# dfp_lc2 <- dfp_lc %>% 
#   mutate(gender_b = as.numeric(case_when(
#     dem_gender_1_b == 1 ~ 1, # man
#     dem_gender_2_b == 1 ~ 2, # nb
#     dem_gender_5_b == 1 ~ 3, # woman
#     dem_gender_3_b == 1 ~ 4, # other
#     dem_gender_4_b == 1 ~ 5 # prefer not to answer
#   )))

df_gender <- dfp_lc2 %>% 
  group_by(gender_b) %>% 
  summarise(n = n(),
            percent = round(100 *(n()/nrow(dfp_lc2)),2))
```

```{r race, echo=F}
# dfp_lc2 <- dfp_lc2 %>% 
#   mutate(race_b = as.numeric(case_when(
#     dem_race_1_b == 1 ~ 1, # white
#     dem_race_2_b == 1 ~ 2, # black
#     dem_race_3_b == 1 ~ 3, # hispanic
#     dem_race_4_b == 1 ~ 4, # asian
#     dem_race_5_b == 1 ~ 5, # nh/pi
#     dem_race_6_b == 1 ~ 6, # ai
#     dem_race_7_b == 1 ~ 7, # eskimo
#     dem_race_8_b == 1 ~ 8, # other
#     dem_race_9_b == 1 ~ 9 # prefer not to answer
#   )))

df_race <- dfp_lc2 %>% 
  group_by(race_b) %>% 
  summarise(n = n(),
            percent = round(100 *(n()/nrow(dfp_lc2)),2))
```

```{r echo=F}
scrpm_tab <- dfp_lc2 %>% 
  mutate(RPM = rav_scored,
         SciCuriosity = sc_scored,
         ArcticIce = arctic20,
         GlobalTemp = temp20,
         OzoneHole = ozone20,
         AirQuality = airqual20,
         CO2 = co220,
         IceSheets = icesheets20,
         BacteriaPop = diatho20,
         EarthquakeMag = quake20) %>% 
  select(SciCuriosity, RPM, ArcticIce, GlobalTemp, OzoneHole, AirQuality, IceSheets, BacteriaPop, EarthquakeMag) %>% 
  psych::describe() %>% 
  mutate(Min = min,
         Max = max,
         Mean = round(mean, 2),
         SD = round(sd, 2),
         Median = median,
         Skew = round(skew, 2)) %>% 
  as.data.frame() %>% 
  select(Min, Max, SD, Mean, Median, Skew) %>% 
  kable()
```

```{r echo=F, eval=F}
rcorr(dfp_lc2$sc_scored, dfp_lc2$rav_scored)

sc_1 <- lm(sc_scored ~ 1, dfp_lc2)
summary(sc_1)
scrpm <- lm(sc_scored ~ 1 + rav_scored, dfp_lc2)
summary(scrpm)
anova(sc_1, scrpm)
```

```{r echo=F}
dfp_corr <- dfp_lc2 %>% 
  select(conservatism_f, sc_scored, rav_scored, arctic20, temp20, ozone20, airqual20, co220, icesheets20, diatho20, quake20) %>% 
  mutate(Con = conservatism_f,
         SciCur = sc_scored,
         RPM = rav_scored,
         Arctic = arctic20,
         Temp = temp20,
         Ozone = ozone20,
         AirQual = airqual20,
         CO2 = co220,
         IceSheets = icesheets20,
         Bacteria = diatho20,
         Quake = quake20) %>% 
  select(-contains("20"), -contains("scored"), -contains("_f"))

get_upper_tri <- function(cormat){
    cormat[lower.tri(cormat)]<- NA
    return(cormat)
  }

cormap <- cor(dfp_corr) %>% 
  get_upper_tri() %>% 
  melt() %>% 
  ggplot(aes(x = Var1, y = Var2, fill = value)) +
  geom_tile(color = "white") +
  scale_fill_viridis(limits = c(-1,1), discrete=FALSE, option = "A",
                     name="Pearson\nCorrelation") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 25, vjust = 1, 
    size = 13, hjust = 1)) +
  coord_fixed() +
  geom_text(aes(Var1, Var2, label = round(value, 2)), color = "white", size = 3) +
  theme(
    axis.text.y = element_text(size = 13),
    axis.title.x = element_blank(),
    axis.title.y = element_blank(),
  panel.background = element_blank(),
  panel.grid.major = element_blank())
```

```{r echo=F}
desc_mr_var_names <- dfp_lc2 %>% 
  mutate(RPM = rav_scored,
         SciCuriosity = sc_scored,
         ArcticIce = arctic20,
         GlobalTemp = temp20,
         OzoneHole = ozone20,
         AirQuality = airqual20,
         CO2 = co220,
         IceSheets = icesheets20,
         Bacteria = diatho20,
         Earthquakes = quake20,
         Con = con)

desc_mr_con <- desc_mr_var_names %>% 
  filter(Con == 1) %>% 
  select(SciCuriosity, RPM, ArcticIce, GlobalTemp, OzoneHole, AirQuality, IceSheets, Bacteria, Earthquakes) %>%
  psych::describe()%>% 
  mutate(C_Min = min,
         C_Max = max,
         M_c = round(mean, 2),
         SD_c = round(sd, 2),
         C_Median = median,
         Skew_c = round(skew, 2)) %>% 
  as.data.frame() %>% 
  select(M_c, SD_c, Skew_c)

desc_mr_lib <- desc_mr_var_names %>% 
  filter(Con == -1) %>% 
  select(SciCuriosity, RPM, ArcticIce, GlobalTemp, OzoneHole, AirQuality, IceSheets, Bacteria, Earthquakes) %>%
  psych::describe()%>% 
  mutate(L_Min = min,
         L_Max = max,
         M_l = round(mean, 2),
         SD_l = round(sd, 2),
         L_Median = median,
         Skew_l = round(skew, 2)) %>% 
  as.data.frame() %>% 
  select(M_l, SD_l, Skew_l)

desc_mr <- cbind(desc_mr_con, desc_mr_lib) %>% 
  select(contains("_c"), contains("_l")) %>% 
  kable() %>% 
  add_header_above(c(" " = 1, "Conservative" = 3, "Liberal" = 3))
```

```{r}
desc_long <- desc_mr_var_names %>% 
  pivot_longer(cols = c(SciCuriosity, RPM, ArcticIce, GlobalTemp, OzoneHole, AirQuality, IceSheets, Bacteria, Earthquakes), names_to = "Variable", values_to = "Score")

desc_long_mr <- desc_long %>% 
  filter(Variable != "SciCuriosity" & Variable != "RPM") 

desc_plot_mr <- desc_long_mr %>% 
  ggplot(., aes(x = Variable, y = Score, fill = as.factor(Con))) + 
  geom_bar(stat = "summary", fun.y = "mean", position = "dodge") +
  scale_fill_manual(values = c("deepskyblue3", "brown3"), name = "Ideology", labels = c("Lib", "Con")) +
  theme_bw() +
  scale_y_continuous(limits = c(-3, 1), breaks = seq(from  = -3, to = 1, by = .5)) +  
  labs(title = "Average Scores on Motivated Reasoning Items",
       subtitle = "Higher scores indicate more endpoint bias.",
       y = "Average Score",
       x = "Item") +
  theme(axis.text.x = element_text(angle = 45, size = 12, vjust = .6),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.text = element_text(size = 12),
        legend.title = element_text(size = 12),
        plot.title = element_text(size = 16, face = "bold", hjust = .5),
        plot.subtitle = element_text(size = 12, hjust = .13))
  
desc_long_cont <- desc_long %>% 
  filter(Variable == "SciCuriosity" | Variable == "RPM")

desc_long_cont %>% 
  select(Score) %>% 
  unique()

desc_plot_cont <- desc_long_cont %>% 
  ggplot(., aes(x = as.factor(Con), y = Score, fill = as.factor(Con))) + 
  geom_bar(stat = "summary", fun.y = "mean", position = "dodge") +
  facet_wrap(~Variable, scales = "free_y") +
  scale_x_discrete(labels = c("Lib", "Con")) +
  scale_fill_manual(values = c("deepskyblue3", "brown3")) +
  theme_bw() +
  labs(title = "Average Cognitive Ability and Science Curiosity",
       y = "Average Score",
       x = "Ideology") +
  theme(axis.text.x = element_text(size = 12),
        axis.text.y = element_text(size = 12),
        axis.title.x = element_text(size = 14),
        axis.title.y = element_text(size = 14),
        legend.position = "none",
        plot.title = element_text(size = 16, face = "bold", hjust = .5))
```
